export const AUTO_LOGIN_LOADING = "AUTO_LOGIN_LOADING"
export const AUTO_LOGIN_SUCCESS = "AUTO_LOGIN_SUCCESS"
export const AUTO_LOGIN_FAIL = "AUTO_LOGIN_FAIL"

export const LOGIN_WITH_OAUTH_LOADING = "LOGIN_WITH_OAUTH_LOADING"
export const LOGIN_WITH_OAUTH_SUCCESS = "LOGIN_WITH_OAUTH_SUCCESS"
export const LOGIN_WITH_OAUTH_FAIL = "LOGIN_WITH_OAUTH_FAIL"

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
